steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/flask-asign5/flask-asign5
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/flask-asign5/flask-asign5

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - flask-asign5
      - --image
      - gcr.io/flask-asign5/flask-asign5
      - --region
      - us-central1
      - --platform
      - managed
      - --port
      - "5000"
      - --allow-unauthenticated

images:
  - gcr.io/flask-asign5/flask-asign5

options:
  logging: CLOUD_LOGGING_ONLY
